image: "alpine"
before_script:
  - apk update
  - apk add cmake g++ gcc curl git make libuuid util-linux-dev

stages:
  - test

job:
  stage: test
  script:
    - mkdir -p _build
    - cd _build 
    - cmake -DWITH_TEST=1 ../
    - make
    - make test
  cache:
    paths:
      - "_build"
