image: "ubuntu"
before_script:
  - apt-get update
  - apt-get install cmake clang gcc curl git

stages:
  - test

job:
  stage: test
  script:
    - mkdir -p _build
    - cd _build & cmake ../
    - make
    - make test
  cache:
    paths:
      - "_build"
