image: "ubuntu:16.04"
before_script:
  - apt-get update
  - apt-get -y --force-yes install cmake g++ gcc curl git uuid-dev

stages:
  - test

job:
  stage: test
  script:
    - mkdir -p _build
    - cd _build 
    - cmake -DWITH_TEST=1 ../
    - make
    - make test
  cache:
    paths:
      - "_build"
